// GENERATED by scripts/generate-logo-paths.mjs — do not edit by hand.
// Source: public/brand/illustrations/*.svg and public/brand/logos/badge-black.svg
//
// These are rendered as CSS masks tinted with `currentColor`, so the single black
// source file serves every colorway. The `src` is the mask URL; `ratio` is the
// asset's intrinsic width/height, used to reserve layout space.

export type ArtName = "cactus-flower" | "citrus" | "cow-skull" | "fig-leaf-01" | "fig-leaf-02" | "pomegranate" | "saguaro" | "sun" | "yucca" | "badge";

export const art: Record<ArtName, { src: string; ratio: number }> = {
  "cactus-flower": { src: "/brand/illustrations/cactus-flower.svg", ratio: 0.5988 },
  "citrus": { src: "/brand/illustrations/citrus.svg", ratio: 0.9456 },
  "cow-skull": { src: "/brand/illustrations/cow-skull.svg", ratio: 1.2352 },
  "fig-leaf-01": { src: "/brand/illustrations/fig-leaf-01.svg", ratio: 0.4498 },
  "fig-leaf-02": { src: "/brand/illustrations/fig-leaf-02.svg", ratio: 1.0622 },
  "pomegranate": { src: "/brand/illustrations/pomegranate.svg", ratio: 1.047 },
  "saguaro": { src: "/brand/illustrations/saguaro.svg", ratio: 0.4352 },
  "sun": { src: "/brand/illustrations/sun.svg", ratio: 1.0269 },
  "yucca": { src: "/brand/illustrations/yucca.svg", ratio: 0.6445 },
  "badge": { src: "/brand/logos/badge-black.svg", ratio: 0.6844 },
};

export const illustrationNames = [
  "cactus-flower",
  "citrus",
  "cow-skull",
  "fig-leaf-01",
  "fig-leaf-02",
  "pomegranate",
  "saguaro",
  "sun",
  "yucca",
] as const satisfies readonly ArtName[];
