// GENERATED by scripts/generate-photo-index.mjs — do not edit by hand.
// Editorial metadata lives in ./metadata.ts and is safe to edit.

import type { StaticImageData } from "next/image";
import { photoMetadata, type PhotoCategory, type PhotoMeta, type PhotoTag } from "./metadata";

export type { PhotoCategory, PhotoTag };

import p_a7402189_2 from "./files/a7402189-2.webp";
import p_a7402373_edit from "./files/a7402373-edit.webp";
import p_a7402383 from "./files/a7402383.webp";
import p_a7402385 from "./files/a7402385.webp";
import p_a7402481 from "./files/a7402481.webp";
import p_a7500703_2 from "./files/a7500703-2.webp";
import p_a7500704_2 from "./files/a7500704-2.webp";
import p_a7500738_2 from "./files/a7500738-2.webp";
import p_a7500748 from "./files/a7500748.webp";
import p_a7500769 from "./files/a7500769.webp";
import p_a7500819 from "./files/a7500819.webp";
import p_a7500862 from "./files/a7500862.webp";
import p_denim_daze_06 from "./files/denim-daze-06.webp";
import p_denim_daze_09 from "./files/denim-daze-09.webp";
import p_denim_daze_13 from "./files/denim-daze-13.webp";
import p_denim_daze_18 from "./files/denim-daze-18.webp";
import p_denim_daze_27 from "./files/denim-daze-27.webp";
import p_denim_daze_28 from "./files/denim-daze-28.webp";
import p_denim_daze_46 from "./files/denim-daze-46.webp";
import p_denim_daze_49 from "./files/denim-daze-49.webp";
import p_denim_daze_77 from "./files/denim-daze-77.webp";
import p_dsc_1421 from "./files/dsc-1421.webp";
import p_dsc_1424 from "./files/dsc-1424.webp";
import p_dsc_1426 from "./files/dsc-1426.webp";
import p_dsc_1430 from "./files/dsc-1430.webp";
import p_dsc_1433 from "./files/dsc-1433.webp";
import p_dsc_1435 from "./files/dsc-1435.webp";
import p_dsc_1441 from "./files/dsc-1441.webp";
import p_dsc_1443 from "./files/dsc-1443.webp";
import p_dsc_1450 from "./files/dsc-1450.webp";
import p_dsc_8329 from "./files/dsc-8329.webp";
import p_dsc_8431 from "./files/dsc-8431.webp";
import p_dsc_8488 from "./files/dsc-8488.webp";
import p_dsc_8635 from "./files/dsc-8635.webp";
import p_dsc_8658 from "./files/dsc-8658.webp";
import p_dsc_8740 from "./files/dsc-8740.webp";
import p_dsc_8936 from "./files/dsc-8936.webp";
import p_dsc_8996 from "./files/dsc-8996.webp";
import p_dsc_9006_2 from "./files/dsc-9006-2.webp";
import p_dsc_9070 from "./files/dsc-9070.webp";
import p_dsc_9123 from "./files/dsc-9123.webp";
import p_dsc_9149 from "./files/dsc-9149.webp";
import p_dsc_9252 from "./files/dsc-9252.webp";
import p_dsc_9267 from "./files/dsc-9267.webp";
import p_dsc_9270 from "./files/dsc-9270.webp";
import p_dsc_9288 from "./files/dsc-9288.webp";
import p_dsc_9292 from "./files/dsc-9292.webp";
import p_dsc_9321 from "./files/dsc-9321.webp";
import p_dsc_9333 from "./files/dsc-9333.webp";
import p_dsc_9365 from "./files/dsc-9365.webp";
import p_dsc_9394 from "./files/dsc-9394.webp";
import p_dsc_9456 from "./files/dsc-9456.webp";
import p_dsc_9509 from "./files/dsc-9509.webp";
import p_dscf0005 from "./files/dscf0005.webp";
import p_dscf2069 from "./files/dscf2069.webp";
import p_dscf3201 from "./files/dscf3201.webp";
import p_dscf5779 from "./files/dscf5779.webp";
import p_dscf5969 from "./files/dscf5969.webp";
import p_first_light_09 from "./files/first-light-09.webp";
import p_first_light_13 from "./files/first-light-13.webp";
import p_first_light_17 from "./files/first-light-17.webp";
import p_first_light_38 from "./files/first-light-38.webp";
import p_photo_07_08_2025_11_08_00_34 from "./files/photo-07-08-2025-11-08-00-34.webp";
import p_photo_07_08_2025_11_37_24_99 from "./files/photo-07-08-2025-11-37-24-99.webp";
import p_photo_28_07_2026_14_03_26_0 from "./files/photo-28-07-2026-14-03-26-0.webp";
import p_photo_28_07_2026_14_16_26_73 from "./files/photo-28-07-2026-14-16-26-73.webp";
import p_photo_28_07_2026_14_16_31_69 from "./files/photo-28-07-2026-14-16-31-69.webp";
import p_photo_28_07_2026_14_49_17_38 from "./files/photo-28-07-2026-14-49-17-38.webp";
import p_photo_28_07_2026_15_01_11_79 from "./files/photo-28-07-2026-15-01-11-79.webp";
import p_rambler_x_westbound_052 from "./files/rambler-x-westbound-052.webp";
import p_rambler_x_westbound_094 from "./files/rambler-x-westbound-094.webp";
import p_rambler_x_westbound_097 from "./files/rambler-x-westbound-097.webp";
import p_rambler_x_westbound_102 from "./files/rambler-x-westbound-102.webp";
import p_rambler_x_westbound_198 from "./files/rambler-x-westbound-198.webp";
import p_rambler_x_westbound_200 from "./files/rambler-x-westbound-200.webp";
import p_taylor_schiers_064 from "./files/taylor-schiers-064.webp";
import p_taylor_schiers_076 from "./files/taylor-schiers-076.webp";
import p_taylor_schiers_096 from "./files/taylor-schiers-096.webp";
import p_taylor_schiers_118 from "./files/taylor-schiers-118.webp";

export type Photo = PhotoMeta & {
  /** Stable id, derived from the original filename. */
  slug: string;
  src: StaticImageData;
  width: number;
  height: number;
  orientation: "portrait" | "landscape" | "square";
};

const files_: ReadonlyArray<[string, StaticImageData]> = [
  ["a7402189-2", p_a7402189_2],
  ["a7402373-edit", p_a7402373_edit],
  ["a7402383", p_a7402383],
  ["a7402385", p_a7402385],
  ["a7402481", p_a7402481],
  ["a7500703-2", p_a7500703_2],
  ["a7500704-2", p_a7500704_2],
  ["a7500738-2", p_a7500738_2],
  ["a7500748", p_a7500748],
  ["a7500769", p_a7500769],
  ["a7500819", p_a7500819],
  ["a7500862", p_a7500862],
  ["denim-daze-06", p_denim_daze_06],
  ["denim-daze-09", p_denim_daze_09],
  ["denim-daze-13", p_denim_daze_13],
  ["denim-daze-18", p_denim_daze_18],
  ["denim-daze-27", p_denim_daze_27],
  ["denim-daze-28", p_denim_daze_28],
  ["denim-daze-46", p_denim_daze_46],
  ["denim-daze-49", p_denim_daze_49],
  ["denim-daze-77", p_denim_daze_77],
  ["dsc-1421", p_dsc_1421],
  ["dsc-1424", p_dsc_1424],
  ["dsc-1426", p_dsc_1426],
  ["dsc-1430", p_dsc_1430],
  ["dsc-1433", p_dsc_1433],
  ["dsc-1435", p_dsc_1435],
  ["dsc-1441", p_dsc_1441],
  ["dsc-1443", p_dsc_1443],
  ["dsc-1450", p_dsc_1450],
  ["dsc-8329", p_dsc_8329],
  ["dsc-8431", p_dsc_8431],
  ["dsc-8488", p_dsc_8488],
  ["dsc-8635", p_dsc_8635],
  ["dsc-8658", p_dsc_8658],
  ["dsc-8740", p_dsc_8740],
  ["dsc-8936", p_dsc_8936],
  ["dsc-8996", p_dsc_8996],
  ["dsc-9006-2", p_dsc_9006_2],
  ["dsc-9070", p_dsc_9070],
  ["dsc-9123", p_dsc_9123],
  ["dsc-9149", p_dsc_9149],
  ["dsc-9252", p_dsc_9252],
  ["dsc-9267", p_dsc_9267],
  ["dsc-9270", p_dsc_9270],
  ["dsc-9288", p_dsc_9288],
  ["dsc-9292", p_dsc_9292],
  ["dsc-9321", p_dsc_9321],
  ["dsc-9333", p_dsc_9333],
  ["dsc-9365", p_dsc_9365],
  ["dsc-9394", p_dsc_9394],
  ["dsc-9456", p_dsc_9456],
  ["dsc-9509", p_dsc_9509],
  ["dscf0005", p_dscf0005],
  ["dscf2069", p_dscf2069],
  ["dscf3201", p_dscf3201],
  ["dscf5779", p_dscf5779],
  ["dscf5969", p_dscf5969],
  ["first-light-09", p_first_light_09],
  ["first-light-13", p_first_light_13],
  ["first-light-17", p_first_light_17],
  ["first-light-38", p_first_light_38],
  ["photo-07-08-2025-11-08-00-34", p_photo_07_08_2025_11_08_00_34],
  ["photo-07-08-2025-11-37-24-99", p_photo_07_08_2025_11_37_24_99],
  ["photo-28-07-2026-14-03-26-0", p_photo_28_07_2026_14_03_26_0],
  ["photo-28-07-2026-14-16-26-73", p_photo_28_07_2026_14_16_26_73],
  ["photo-28-07-2026-14-16-31-69", p_photo_28_07_2026_14_16_31_69],
  ["photo-28-07-2026-14-49-17-38", p_photo_28_07_2026_14_49_17_38],
  ["photo-28-07-2026-15-01-11-79", p_photo_28_07_2026_15_01_11_79],
  ["rambler-x-westbound-052", p_rambler_x_westbound_052],
  ["rambler-x-westbound-094", p_rambler_x_westbound_094],
  ["rambler-x-westbound-097", p_rambler_x_westbound_097],
  ["rambler-x-westbound-102", p_rambler_x_westbound_102],
  ["rambler-x-westbound-198", p_rambler_x_westbound_198],
  ["rambler-x-westbound-200", p_rambler_x_westbound_200],
  ["taylor-schiers-064", p_taylor_schiers_064],
  ["taylor-schiers-076", p_taylor_schiers_076],
  ["taylor-schiers-096", p_taylor_schiers_096],
  ["taylor-schiers-118", p_taylor_schiers_118],
];

export const photos: readonly Photo[] = files_.map(([slug, src]) => {
  const meta = photoMetadata[slug];
  if (!meta) {
    throw new Error(
      `No metadata for photo "${slug}". Add an entry to src/photos/metadata.ts.`,
    );
  }
  return {
    ...meta,
    slug,
    src,
    width: src.width,
    height: src.height,
    orientation:
      src.height > src.width ? "portrait" : src.width > src.height ? "landscape" : "square",
  };
});

const bySlug = new Map(photos.map((p) => [p.slug, p]));

/** Look up one photo. Throws on an unknown slug so typos fail at render, not silently. */
export function photo(slug: string): Photo {
  const found = bySlug.get(slug);
  if (!found) throw new Error(`Unknown photo "${slug}".`);
  return found;
}

export const byCategory = (...c: PhotoCategory[]) =>
  photos.filter((p) => c.includes(p.category));

export const byTag = (...t: PhotoTag[]) =>
  photos.filter((p) => t.some((tag) => p.tags?.includes(tag)));

export const bySeries = (series: string) =>
  photos.filter((p) => p.series === series);

export const seriesNames: readonly string[] = [
  ...new Set(photos.flatMap((p) => (p.series ? [p.series] : []))),
].sort();

/**
 * PLACE → PERSON → DETAIL → WORK, repeating. Draws from the pools in order so a run of
 * images alternates instead of clumping — the editorial rhythm in docs/DIRECTION.md.
 * Falls back to any remaining photo once a pool runs dry.
 */
export function editorialRhythm(count: number, from: readonly Photo[] = photos): Photo[] {
  const order: PhotoCategory[] = ["place", "person", "detail", "work"];
  const pools = new Map(order.map((c) => [c, from.filter((p) => p.category === c)]));
  const cursors = new Map(order.map((c) => [c, 0]));
  const used = new Set<string>();
  const out: Photo[] = [];

  for (let i = 0; out.length < count && i < count * order.length; i++) {
    const c = order[i % order.length];
    const pool = pools.get(c)!;
    const cursor = cursors.get(c)!;
    if (cursor < pool.length) {
      cursors.set(c, cursor + 1);
      out.push(pool[cursor]);
      used.add(pool[cursor].slug);
    }
  }
  for (const p of from) {
    if (out.length >= count) break;
    if (!used.has(p.slug)) out.push(p);
  }
  return out.slice(0, count);
}
